---
- 
  hosts: all
  become: true
  tasks:
      - name: create a container
        docker_container:
          name: nodejs
          image: 180030469/devops/nodejs
          state: present
          recreate: yes
          exposed_ports:
            - 8090
